artworks/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('collection.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(
        template_name='registration/login.html')),
    path('accounts/logout/', auth_views.LogoutView.as_view()),
]

collection/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("artwork/<int:artwork_id>", views.artwork, name="artwork"),
    path("artworks/search", views.search_artworks, name="search_artworks"),
    path("accounts/profile/", views.index, name="profile"),  
    path("accounts/register/", views.register, name="register"),
    path("artworks/random", views.random_artworks, name="random_artworks"), 
    path("collections/", views.collections, name="collections"),
    path("collection_list/", views.collection_list, name="collection_list"),
    path("collection/add", views.collection_add, name="collection_add"),
    path('collection/<int:collection_id>/', views.details, name='details'),
    path('artwork/<int:artwork_id>/add-to-collection/', views.add_to_collection, name='add_to_collection'),
    path('collection/<int:collection_id>/remove/<int:artwork_id>/', views.remove_from_collection, name='remove_from_collection'),
    path('collection/<int:collection_id>/edit/', views.collection_edit, name='collection_edit'),
    path('collection/remove/<int:collection_id>/', views.remove_collection, name='remove_collection'),
    path('artist_artworks/<slug:artist_slug>/', views.artist_artworks, name='artist_artworks'),



]

collection/models.py
from django.db import models
from django.contrib.auth.models import User


class Artist(models.Model):
    slug = models.SlugField(max_length=80, unique=True)
    name = models.CharField(max_length=80)
    born_date = models.CharField(max_length=40)


class Genre(models.Model):
    name = models.CharField(max_length=40, unique=True)


class Style(models.Model):
    name = models.CharField(max_length=40, unique=True)


class Period(models.Model):
    name = models.CharField(max_length=120, unique=True)


class Artwork(models.Model):
    author = models.ForeignKey(Artist, on_delete=models.RESTRICT)
    path = models.CharField(max_length=200, unique=True)
    title = models.CharField(max_length=400)
    date = models.CharField(max_length=40, null=True)
    style = models.ForeignKey(Style, null=True, on_delete=models.RESTRICT)
    period = models.ForeignKey(Period, null=True, on_delete=models.RESTRICT)
    genre = models.ForeignKey(Genre, null=True, on_delete=models.RESTRICT)
    image_url = models.URLField()


class Collection(models.Model):
    owner = models.ForeignKey(User, on_delete=models.RESTRICT)
    artworks = models.ManyToManyField(Artwork)
    name = models.CharField(max_length=80)
    description = models.TextField(blank=True)

collection/forms.py
from django import forms


class CollectionForm(forms.Form):
    name = forms.CharField(label="Nombre", max_length=80, required=True)
    description = forms.CharField(label="Descripción", required=True)

collection/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.template.loader import render_to_string
from django.contrib.postgres import search 
from django.core.paginator import Paginator
import random
from .models import Artwork, Collection, Artist, Style, Genre
from .forms import CollectionForm

def register(request):
    if request.method == 'POST':
        f = UserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            username = f.cleaned_data.get('username')
            raw_password = f.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)

            return HttpResponseRedirect('/')

    else:
        f = UserCreationForm()

    return render(request, 'registration/registration_form.html', {'form': f})


def artwork(request, artwork_id):
    artwork = Artwork.objects.get(pk=artwork_id)
    collections = Collection.objects.filter(owner=request.user)
    return render(request, 'collection/artwork.html', {'artwork': artwork, 'collections': collections})


def collections(request):
    collections = Collection.objects.filter(owner=request.user)
    return render(request, 'collection/collections.html',
                  {'collections': collections})


def collection_list(request):
    collections = Collection.objects.filter(owner=request.user)
    return render(request, 'collection/collection_list.html',
                  {'collections': collections})


def collection_add(request):
    form = None
    if request.method == 'POST':
        form = CollectionForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            collection = Collection(
                    name=name,
                    description=description,
                    owner=request.user)
            collection.save()
            return HttpResponse(status=204,
                                headers={'HX-Trigger': 'listChanged'})

    return render(request,
                  'collection/collection_form.html',
                  {'form': form})


def index(request):
    artworks = list(Artwork.objects.all())
    random_works = []
    if artworks:
        random_works = random.sample(artworks, 4)
    return render(request, 'collection/index.html', {'artworks': random_works})


def random_artworks(request):
    artworks = list(Artwork.objects.all())
    random_works = []
    if artworks:
        random_works = random.sample(artworks, 4)
    return render(request, 'collection/artworks_random.html',
                  {'artworks': random_works})


def search_artworks(request):
    if request.method == 'GET':
        value = request.GET['search']
        artworks = ft_artworks(value)

        paginator = Paginator(artworks, 4)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        return render(request, 'collection/artwork_search.html',
                      {'artworks': artworks, 'search_value': value,
                       "page_obj": page_obj})
    else:
        return render(request, 'collection/index.html',
                      {'artworks': [], 'search_value': None})


def ft_artworks(value):
    vector = (
        search.SearchVector("title", weight="A")
        + search.SearchVector("author__name", weight="B")
        + search.SearchVector("style__name", weight="C")
        + search.SearchVector("genre__name", weight="C")
    )
    query = search.SearchQuery(value, search_type="websearch")
    return (
        Artwork.objects.annotate(
            search=vector,
            rank=search.SearchRank(vector, query),
        )
        .filter(search=query)
        .order_by("-rank")
    )

def remove_collection(request, collection_id):
    collection = get_object_or_404(Collection, pk=collection_id, owner=request.user)
    collection.delete()
    return redirect("collections")

def details(request, collection_id):
    collection = get_object_or_404(Collection, id=collection_id)
    artworks = collection.artworks.all()
    return render(request, 'collection/details.html', {'collection': collection, 'artworks': artworks})

def collection_edit(request, collection_id):
    collection = get_object_or_404(Collection, id=collection_id)
    if request.method == 'POST':
        collection.name = request.POST.get('name')
        collection.description = request.POST.get('description')
        collection.save()
        return  redirect('collections') 
    return render(request, 'collection/collection_edit_form.html', {'collection': collection})


def artist_artworks(request, artist_slug):
    artist = get_object_or_404(Artist, slug=artist_slug)
    artworks = Artwork.objects.filter(author=artist)
    return render(request, 'collection/artist_artworks.html', {'artist': artist, 'artworks': artworks})

def add_to_collection(request, artwork_id):
    if request.method == 'POST':
        artwork = get_object_or_404(Artwork, pk=artwork_id)
        collection_id = request.POST.get('collection_id')
        collection = get_object_or_404(Collection, pk=collection_id, owner=request.user)

        # Agrega la pintura a la colección
        collection.artworks.add(artwork)

        return HttpResponse(status=204, headers={'HX-Trigger': 'listChanged'})

    return HttpResponse(status=400)

def remove_from_collection(request, collection_id, artwork_id):
    collection = get_object_or_404(Collection, pk=collection_id, owner=request.user)
    artwork = get_object_or_404(Artwork, pk=artwork_id)
    # Elimina la pintura de la colección
    collection.artworks.remove(artwork)
    return redirect('details', collection_id=collection_id)

collection/templates/collection/artist_artworks.html
{% extends "collection/base.html" %}
{% block content %}

<div class="flex justify-center md:mx-auto md:max-w-screen-2xl px-2  bg-slate-200">
    <div class="w-full md:w-3/4 lg:w-2/3">
        <br>
        <h2 class="text-gray-900 text-2xl title-font font-medium mb-1 text-center">Obras de {{ artist.name }}</h2>
        {% if artworks %}
        <br>
        <div class="grid grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {% for artwork in artworks %}
            <div
                class="rounded-lg shadow-md p-6 transform scale-100 hover:scale-110 transition-transform bg-slate-300 shadow-outline">
                <a href="/artwork/{{artwork.id}}">
                    <img src="{{ artwork.image_url }}" alt="{{ artwork.title }}" class="w-full h-3/4 object-cover">
                </a>
                <h2 class="text-xl font-semibold mt-2 truncate">{{ artwork.title }}</h2>
                <p class="text-sm text-gray-600 truncate">
                    Artista: {{artwork.author.name}}</p>
                <p class="text-sm text-gray-600 truncate">Estilo: {{ artwork.style.name }}</p>
                <p class="text-sm text-gray-600 truncate">Género: {{ artwork.genre.name }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
</div>

</div>

{% endblock content %}

collection/templates/collection/artwork.html
{% extends "collection/base.html" %}
{% block content %}
<div class="container flex mx-auto px-5 py-2 lg:px-32 lg:pt-12 ">
    <div class="overflow-hidden rounded-lg bg-white shadow w-1/2 h-full">
        <div class="px-4 py-5 sm:p-6">
            <div class="w-full p-1 md:p-2">
                <img class="block h-full w-full rounded-lg object-cover object-center" src="{{artwork.image_url}}"
                    alt="{{artwork.title}}" />
            </div>
        </div>
        <div class="bg-gray-50 px-4 py-4 sm:px-6">
            <div class="flex justify-end items-center">
                <button onclick="showCollectionModal()"
                    class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
                    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        class="w-5 h-5" viewBox="0 0 24 24">
                        <path
                            d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z">
                        </path>
                    </svg>
                </button>
            </div>
            <div class=" -m-1 h-12 mt-1 mb-5 ">
                <p class="mt-3 pl-8 text-gray-600 font-thin"> Data from: </p>
                <a href="https://www.wikiart.org{{artwork.path}}" class="block overflow-hidden
                        text-ellipsis pl-5 text-sky-600 pb-5"> www.wikiart.org{{artwork.path}} </a>
            </div>
        </div>
    </div>
    <div class="overflow-hidden w-1/3 h-64">
        <div class="px-4 py-4 sm:px-6">
            <div class=" -m-1 h-10 mt-1 mb-5 ">
                <p class="block overflow-hidden
                        text-ellipsis pl-5 dark:text-gray-200 text-3xl font-bold"> {{artwork.title}} </p>
                <a href="#" class="block pl-5 text-2xl text-sky-600 "> {{artwork.author.name}} </a>
                <p class="mt-3 pl-8 text-gray-600 font-thin"> Date: {{artwork.date}} </p>
                <p class="mt-2 pl-8 text-gray-600 font-thin"> Style: {{artwork.style.name}} </p>
                <p class="mt-2 pl-8 text-gray-600 font-thin"> Period: {{artwork.period.name}} </p>
                <p class="mt-3 pl-8 text-gray-600 font-thin"> Genre: {{artwork.genre.name}} </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

collection/templates/collection/artwork_search.html
{% extends "collection/base.html" %}

{% block content %}

<div class="container mx-auto px-5 py-2 lg:px-32 lg:pt-12">
  <div class="-m-1 flex flex-wrap md:-m-2">
    {% for artwork in page_obj %}  
    <div class="flex w-1/4 flex-wrap pt-3">
      <div class="w-full p-1 md:p-2">
        <img
          class="block h-full w-full rounded-lg object-cover object-center"
          src="{{artwork.image_url}}" alt="{{artwork.title}}" />
      </div>
      <div  class=" -m-1 h-10 mt-1 mb-5 "> 
                <a href="/artwork/{{artwork.id}}" class="block overflow-hidden
                    text-ellipsis pl-5 text-sky-600 font-bold"> {{artwork.title|truncatechars_html:40}}  </a>
                <a href="#"  class="block pl-5"> {{artwork.author.name}} 
                    <span class="text-gray-400 text-sm font-thin"> {{artwork.date}} </span> </a>
      </div>
    </div>
    {% endfor %} 
  </div>
    <nav class="flex items-center justify-between border-t border-gray-200 bg-white px-4 py-3 sm:px-6 mt-8" aria-label="Pagination">
      <div class="hidden sm:block">
        <p class="text-sm text-gray-700">
          Showing page
          <span class="font-medium">{{ page_obj.number }}</span>
          of
          <span class="font-medium">{{ page_obj.paginator.num_pages }}</span>
        </p>
      </div>
      <div class="flex flex-1 justify-between sm:justify-end">
    {% if page_obj.has_previous %}
        <a href="?search={{ search_value|stringformat:'s'}}&page={{ page_obj.previous_page_number }}" class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">Previous</a>
    {% endif %}
    {% if page_obj.has_next %}
        <a href="?search={{ search_value|stringformat:'s'}}&page={{ page_obj.next_page_number }}" class="relative ml-3 inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">Next</a>
      </div>
    {% endif %}
    </nav>
</div>
{% endblock content %}

collection/templates/collection/artworks_random.html
{% for artwork in artworks %}  
    <div class="flex w-1/4 flex-wrap pt-3">
      <div class="w-full p-1 md:p-2">
        <img
          class="block h-full w-full rounded-lg object-cover object-center"
          src="{{artwork.image_url}}" alt="{{artwork.title}}" />
      </div>
      <div  class=" -m-1 h-10 mt-1 mb-5 "> 
                <a href="/artwork/{{artwork.id}}" class="block overflow-hidden
                    text-ellipsis pl-5 text-sky-600 font-bold"> {{artwork.title|truncatechars_html:40}}  </a>
                <a href="#"  class="block pl-5"> {{artwork.author.name}} 
                    <span class="text-gray-400 text-sm font-thin"> {{artwork.date}} </span> </a>
      </div>
    </div>
{% endfor %} 

collection/templates/collection/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">  
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link href="{% static 'output.css' %}" rel="stylesheet" />

    {% block head %}

    {% endblock head %}
    <title> artworks </title>

      <script>
      /*to prevent Firefox FOUC, this must be here*/
        let FF_FOUC_FIX;
      </script>
     <style>

         {% block style %}

         {% endblock style %}
      </style>
  </head>

  <body class="bg-white dark:bg-slate-900" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    {% block header %}
      {% include "collection/header.html" %} 
    {% endblock header %}


    {% block content %}

    {% endblock content %}

   


    {% block footer%}
<footer class="bg-white">
  <div class="mx-auto max-w-7xl overflow-hidden px-6 py-20 sm:py-24 lg:px-8">
    <nav class="-mb-6 columns-2 sm:flex sm:justify-center sm:space-x-12" aria-label="Footer">
      <div class="pb-6">
        <a href="https://github.com/Richierl/Proyecto_3" class="text-sm leading-6 text-gray-600 hover:text-gray-900">GitHub</a>
      </div>
      <div class="pb-6">
        <a href="https://www.wikiart.org/" class="text-sm leading-6 text-gray-600 hover:text-gray-900"> wikiart.org </a>
      </div>
    </nav>
   
    <p class="mt-10 text-center text-xs leading-5 text-gray-500">&copy; Ricardo, Gerardo, José Carlos</p>
  </div>
</footer>

    {% endblock footer %}

  <script src="https://unpkg.com/hyperscript.org@0.9.7"></script>
  <script src="https://unpkg.com/htmx.org@1.8.5" integrity="sha384-7aHh9lqPYGYZ7sTHvzP1t3BAfLhYSTy9ArHdP3Xsr9/3TlGurYgcPBoFmXX2TX/w" crossorigin="anonymous"></script>

  {% block scripts %}

  {% endblock scripts %}

</body>
</html>

collection/templates/collection/collection_edit_form.html
{% extends "collection/base.html" %}

{% block content %}
<div class="max-w-md mx-auto mt-8 p-6 bg-white rounded-md shadow-md">
    <h2 class="text-2xl font-bold mb-4">Editar Colección</h2>

    <form method="post" action="{% url 'collection_edit' collection.id %}" class="space-y-4">
        {% csrf_token %}

        <div>
            <label for="id_name" class="block text-sm font-medium text-gray-600">Nombre:</label>
            <input type="text" name="name" id="id_name" value="{{ collection.name }}" required
                class="mt-1 p-2 block w-full border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500 focus:ring focus:ring-indigo-200">
        </div>

        <div>
            <label for="id_description" class="block text-sm font-medium text-gray-600">Descripción:</label>
            <textarea name="description" id="id_description" required
                class="mt-1 p-2 block w-full border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500 focus:ring focus:ring-indigo-200">{{ collection.description }}</textarea>
        </div>

        <div>
            <button type="submit"
                class="px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-500 focus:outline-none focus:bg-indigo-500">
                Guardar cambios
            </button>
        </div>
    </form>
</div>
{% endblock %}

collection/templates/collection/collection_form.html
<div id="modal" _="on closeModal or listChanged remove me" 
    class="relative z-10" role="dialog" aria-modal="true">
  <div class="fixed inset-0 hidden bg-gray-500 bg-opacity-75 transition-opacity md:block"></div>
        <div class="fixed inset-0 z-10 w-screen overflow-y-auto">

<div class="flex w-full mx-auto transform 
            text-left text-base transition 
            md:my-8 md:max-w-2xl md:px-4 lg:max-w-4xl">
         
        <div class="relative flex w-full 
                items-center overflow-hidden bg-white 
                px-4 pb-8 pt-14 shadow-2xl sm:px-6 sm:pt-8 md:p-6 lg:p-8">
          
        <form hx-post="/collection/add" hx-target="#modal" hx-swap="outerHTML" 
            class="bg-white  w-full  md:col-span-2">
            <div class="px-4 py-3 sm:p-8">
                <p class="block overflow-hidden
                        text-ellipsis mb-4 dark:text-gray-200 text-xl font-bold"> Agrega una Colección  </p>
             <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                   <div class="sm:col-span-4">

                      <label for="name" class="block 
                                        text-sm font-medium 
                                        leading-6 text-gray-900">Nombre</label>
                      <div class="mt-2">
                            <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 
                                    focus-within:ring-2 focus-within:ring-inset 
                                    focus-within:ring-indigo-600
                                sm:max-w-md">
                            <input type="text" name="name" id="name" 
                               class="block flex-1 border-0 bg-transparent py-1.5 pl-1 
                                    text-gray-900 placeholder:text-gray-400 focus:ring-0 
                                    sm:text-sm sm:leading-6"
                                 value='{{form.name.value}}'>
                            </div>
                            <div class="text-sm font-medium text-red-600">
                                {{ form.name.errors }}
                            </div>
                      </div>
                  </div>

                  <div class="col-span-full">
                    <label for="description" class="block text-sm font-medium
                                    leading-6 text-gray-900">Descripción</label>
                    <div class="mt-2">
                      <textarea id="description" name="description" rows="3" 
                        class="block w-full rounded-md border-0 py-1.5 
                        text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 
                        placeholder:text-gray-400 focus:ring-2 focus:ring-inset
                        focus:ring-indigo-600 sm:text-sm sm:leading-6"
                        >{{form.description.value}}</textarea>
                    </div>
                            <div class="text-sm font-medium text-red-600">
                                {{ form.description.errors }}
                            </div>
                </div>
            </div>
         <div class="mt-6 mr-3 flex items-center justify-end gap-x-6">
            <button type="button"  
                    _="on click trigger closeModal" 
                    class="text-sm font-semibold leading-6 text-gray-900">Cancelar</button>
            <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Guardar</button>
          </div>
        </form>


            </div>
        </div>
    </div>
        </div>
    </div>

collection/templates/collection/collection_list.html
{% for collection in collections %}
<tr class="hover:bg-gray-100">
  <td class="py-2 px-4 text-sm font-medium text-gray-900">{{collection.name}}</td>
  <td class="py-2 px-4 text-sm text-gray-500">{{collection.description}}</td>
  <td class="py-2 px-4 text-right text-sm font-medium">
    <a href="{% url 'details' collection.id %}" class="text-indigo-600 hover:text-indigo-900">Ver
      Pinturas<span class="sr-only">, {{collection.name}}</span></a>
  </td>
  <td class="py-2 px-4 text-right text-sm font-medium">
    <a href="{% url 'collection_edit' collection.id %}" class="text-indigo-600 hover:text-indigo-900">Editar<span
        class="sr-only">, {{collection.name}}</span></a>
  </td>
  <td class="py-2 px-4 text-right text-sm font-medium">
    <a href="{% url 'remove_collection' collection.id %}" class="text-indigo-600 hover:text-indigo-900">
        <span class="text-sm">Eliminar</span>
      </button>
    </a>
  </td>
</tr>
{% endfor %}

collection/templates/collection/collections.html
{% extends "collection/base.html" %}

{% block content %}
<div class="container mx-auto px-5 py-2 lg:px-32 lg:pt-12">
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Colecciones</h1>
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
      <button type="button" class="block rounded-md bg-indigo-600 px-3
                    py-2 text-center text-sm font-semibold text-white 
                    shadow-sm hover:bg-indigo-500 focus-visible:outline 
                    focus-visible:outline-2 focus-visible:outline-offset-2 
                    focus-visible:outline-indigo-600"
                   hx-get="/collection/add" hx-target="body" hx-swap="beforeend" 
                >Agrega una colección</button>
    </div>
   
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Name</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Description</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody  hx-trigger="listChanged from:body" 
                  hx-get="{% url 'collection_list' %}" hx-target="this" class="divide-y divide-gray-200">
         {% include "collection/collection_list.html" %}              
         </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

collection/templates/collection/details.html
{% extends "collection/base.html" %}
{% block content %}
<div class="flex justify-center items-center md:mx-auto md:max-w-screen-2xl px-2 bg-slate-200 ">
    <div class="w-full md:w-3/4 lg:w-2/3">
        <br>
        <h2 class="text-gray-900 text-2xl title-font font-medium mb-1 text-center">COLECCION</h2>
        <h2 class="text-sm title-font text-gray-500 tracking-widest text-center">{{ collection.name }}</h2>
        {% if artworks %}
        <div class="grid grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {% for artwork in artworks %}
            <div
                class="relative rounded-lg shadow-md p-6 transform scale-100 hover:scale-110 transition-transform bg-slate-300 shadow-outline">
                <a href="/artwork/{{artwork.id}}">
                    <img src="{{ artwork.image_url }}" alt="{{ artwork.title }}" class="w-full h-3/4 object-cover">
                </a>
                <form action="{% url 'remove_from_collection' collection.id artwork.id %}" method="post"
                    class="absolute bottom-2 right-2">
                    {% csrf_token %}
                    <button class="btn btn-square btn-outline">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-500 hover:text-red-600"
                            fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </form>
                <div class="mt-2">
                    <h2 class="text-xl font-semibold truncate">{{ artwork.title }}</h2>
                    <p class="text-sm text-gray-600 truncate">Artista: {{ artwork.author.name }}</p>
                    <p class="text-sm text-gray-600 truncate">Estilo: {{ artwork.style.name }}</p>
                    <p class="text-sm text-gray-600 truncate">Género: {{ artwork.genre.name }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p class="text-center text-gray-500">No hay pinturas en esta colección.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

collection/templates/collection/index.html
{% extends "collection/base.html" %}
{% block content %}

<div class="container mx-auto px-5 py-2 lg:px-32 lg:pt-12">
  <div id="artworks-container" class="-m-1 flex flex-wrap md:-m-2">
    {% for artwork in artworks %}  
    <div class="flex w-1/4 flex-wrap pt-3">
      <div class="w-full p-1 md:p-2">
        <img
          class="block h-full w-full rounded-lg object-cover object-center"
          src="{{artwork.image_url}}" alt="{{artwork.title}}" />
      </div>
      <div  class=" -m-1 h-10 mt-1 mb-5 "> 
                <a href="/artwork/{{artwork.id}}" class="block overflow-hidden
                    text-ellipsis pl-5 text-sky-600 font-bold"> {{artwork.title|truncatechars_html:40}}  </a>
                <a href="#"  class="block pl-5"> {{artwork.author.name}} 
                    <span class="text-gray-400 text-sm font-thin"> {{artwork.date}} </span> </a>
      </div>
    </div>
    {% endfor %} 
  </div>

</div>
{% endblock content %}